### ISSUE TITLE
sdk安装后无法正常启动项目

### ISSUE THREAD

**Issue by tongliwei123** [GuanceCloud/datakit-flutter#1]
![image](https://github.com/GuanceCloud/datakit-flutter/assets/24215554/2c31cf47-346f-4283-af30-d9290df0558e)
最新的三个版本都无法正常启动，报错如上

**Comment by Br4ndonZhang** [comment]
目前我们 SDK 最佳运行版本是 Flutter 3.0，目前有兼容方式支持 2.0 版本，用以下方式集成即可，只是一些兼容处理，使用逻辑不变

```yaml
  ft_mobile_agent_flutter:
    git:
      url: https://github.com/GuanceCloud/datakit-flutter.git
      ref: agent_legacy_0.4.1.dev.1
```
